-- Inserción de datos categorias
INSERT INTO categories (nombre, descripcion, imagen, activo) VALUES ('Arábica', 'Cafés de variedad arábica...', null, true);
INSERT INTO categories (nombre, descripcion, imagen, activo) VALUES ('Robusto', 'Cafés de variedad robusta...', null, true);
INSERT INTO categories (nombre, descripcion, imagen, activo) VALUES ('Tueste Claro', 'Cafés con tueste claro...', null, true);
INSERT INTO categories (nombre, descripcion, imagen, activo) VALUES ('Tueste Oscuro', 'Cafés con tueste oscuro...', null, true);

-- Inserción de datos de los productos
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004230', 'Café Arábica Etiopía', 'CaféOrigen', 'Café de especialidad procedente de las tierras altas de Etiopía, cultivado a más de 1800 metros de altitud. Sus granos presentan notas florales intensas, con toques de jazmín y bergamota, acompañados de una acidez brillante y un dulzor natural que recuerda a los frutos rojos maduros. Ideal para métodos de extracción en frío o pour over.', '/images/productos/cafe.webp', 12.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004247', 'Café Robusta Uganda', 'CaféOrigen', 'Robusta ugandés de gran cuerpo y elevado contenido en cafeína. Perfecto para espresso intenso.', '/images/productos/cafe.webp', 9.95, 10);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004254', 'Café Tueste Claro Colombia', 'Montaña Verde', 'Café colombiano con tueste claro que preserva todas las notas frutales y florales del grano. Cultivado en la región de Huila, presenta una taza limpia con acidez cítrica, notas de melocotón y un retrogusto dulce y prolongado. Recomendado para filtro o aeropress.', null, 11.50, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004261', 'Café Tueste Oscuro Brasil', 'Montaña Verde', 'Tueste oscuro brasileño con notas de chocolate y caramelo.', null, 8.75, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004278', 'Café Guatemala Antigua', 'CaféOrigen', 'Procedente de la región de Antigua en Guatemala, este café de tueste medio ofrece una taza equilibrada con notas de chocolate con leche, nuez moscada y una suave acidez. Su cultivo en suelos volcánicos le aporta una mineralidad característica que lo distingue de otros cafés centroamericanos.', '/images/productos/cafe.webp', 13.50, 15);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004285', 'Café Kenya AA', null, 'Café keniano de grado AA, el más alto en clasificación. Notas de grosella negra y tomate.', '/images/productos/cafe.webp', 14.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004292', 'Café Yemen Moka', null, 'El legendario café de Yemen, considerado uno de los más antiguos del mundo. Su proceso de secado natural al sol le aporta una complejidad única, con notas de vino tinto, especias y cacao. Un café para los más aventureros y curiosos del mundo del café de especialidad.', null, 18.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004308', 'Café Vietnam Robusta', null, 'Robusta vietnamita de sabor intenso y gran cuerpo. Sin marca ni imagen.', null, 7.50, 5);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004315', 'Blend Espresso Clásico', 'BaristaPro', 'Mezcla de arábica y robusta especialmente diseñada para espresso. Equilibrio perfecto entre cuerpo, crema y aroma. Una combinación de granos de Brasil, Colombia y Uganda que ofrece una taza con notas de avellana, chocolate negro y un final largo y persistente. La elección de los baristas profesionales.', '/images/productos/cafe.webp', 10.95, 20);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004322', 'Café Descafeinado Colombia', 'BaristaPro', 'Descafeinado mediante proceso natural con agua, sin químicos. Conserva todo el sabor.', '/images/productos/cafe.webp', 10.50, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004339', 'Café Peru Orgánico', 'TierraViva', 'Café orgánico certificado procedente de pequeños productores del norte de Perú. Cultivado sin pesticidas ni fertilizantes químicos, con prácticas de agricultura sostenible. Presenta notas de frutos secos, miel y un toque de canela con una acidez moderada y muy agradable.', null, 12.25, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004346', 'Café Bolivia Geisha', 'TierraViva', 'Variedad geisha de Bolivia, escasa y muy apreciada por los catadores.', null, 22.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004353', 'Café Sumatra Mandheling', null, 'El Sumatra Mandheling es uno de los cafés indonesios más reconocidos del mundo. Su proceso húmedo le confiere un cuerpo denso y aterciopelado, con notas de tierra, cedro, tabaco y un dulzor a chocolate oscuro. Bajo en acidez, ideal para quienes prefieren cafés con mucho cuerpo.', '/images/productos/cafe.webp', 13.75, 10);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004360', 'Café Hawái Kona', null, 'Café de las laderas del volcán Mauna Loa. Suave, aromático y muy escaso.', '/images/productos/cafe.webp', 29.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004377', 'Café Jamaica Blue Mountain', 'IslandCoffee', 'El Jamaica Blue Mountain es considerado por muchos como el mejor café del mundo. Cultivado en las montañas Blue Mountain de Jamaica a más de 2000 metros, produce una taza extremadamente suave, sin amargor, con notas florales, cítricos y una dulzura natural excepcional.', '/images/productos/cafe.webp', 34.95, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004384', 'Café India Monzón Malabar', 'IslandCoffee', 'Café sometido al proceso de monzón, que le da un sabor único y terroso.', null, 11.95, 5);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004391', 'Café Nicaragua Matagalpa', 'Montaña Verde', 'Café nicaragüense de la región de Matagalpa, con tueste medio y notas de caramelo, almendra y una acidez suave y redonda. Producido por cooperativas locales con comercio justo certificado, lo que garantiza condiciones dignas para los agricultores y sus familias.', '/images/productos/cafe.webp', 10.75, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004407', 'Café Costa Rica Tarrazú', null, 'Costa Rica Tarrazú, uno de los cafés más equilibrados de Centroamérica.', null, 12.50, 0);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004414', 'Blend Desayuno Intenso', 'BaristaPro', 'Mezcla de tueste oscuro pensada para el desayuno. Gran cuerpo y mucha cafeína para empezar el día con energía. Combina robusta de Uganda con arábica de Brasil en una proporción 60/40 que garantiza una crema densa y un sabor potente que aguanta bien la leche.', '/images/productos/cafe.webp', 8.95, 25);
INSERT INTO products (codigo_ean, nombre, marca, descripcion, imagen, precio, descuento) VALUES ('8410285004421', 'Café Tanzania Peaberry', 'CaféOrigen', 'El Peaberry es un grano especial que se forma cuando solo se desarrolla una semilla dentro de la cereza del café. El Tanzania Peaberry ofrece una concentración de sabores superior, con notas de ciruela, frambuesa y un final largo con toques de chocolate con leche.', '/images/productos/cafe.webp', 15.95, 0);